tracks_dir: /Users/<your-system-username>/<your-tracks-dir>
output: results.html
spotify:
  username: <your-spotify-username>
  client_id: <your-spotify-client-id>
  client_secret: <your-spotify-client-secret>
